version: "3.9"

services:
  web:
    build: .
    image: n8n-clientes:latest
    container_name: n8n-clientes-web
    ports:
      - "5080:8000"   # local dev
    environment:
      SECRET_KEY: "${SECRET_KEY:-change-in-prod}"
      DATABASE_URL: "${DATABASE_URL}"
      PAGE_SIZE: "${PAGE_SIZE:-10}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/"]
      interval: 30s
      timeout: 3s
      retries: 3

# Opcional: adicionar Postgres se necessário
#  db:
#    image: postgres:16
#    environment:
#      POSTGRES_USER: "zaza"
#      POSTGRES_PASSWORD: "postgres"
#      POSTGRES_DB: "n8n"
#    ports:
#      - "5439:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data
#    restart: unless-stopped
#
# volumes:
#   pgdata:
